version: "3.8"

services:
  medicaments-api:
    image: node:20-alpine
    container_name: medicaments-api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    restart: unless-stopped
    command: >
      sh -c "
        # Installation des outils nécessaires (incluant iconv pour la conversion d'encodage)
        apk add --no-cache git curl file &&

        # Cloner le repository
        cd /tmp &&
        git clone https://github.com/Gizmo091/fr.gouv.medicaments.rest.git app &&
        cd app &&

        # Installer les dépendances
        npm install --production &&

        # Copier les données existantes si elles existent
        if [ -d /app/data ]; then
          cp -r /app/data/* /tmp/app/data/ 2>/dev/null || true
        fi &&

        # Se déplacer dans le répertoire de l'app
        cd /tmp/app &&

        # Démarrer l'application
        npm start
      "
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "wget --quiet --tries=1 --spider http://localhost:${PORT:-3000}/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
